---
name: betweenness_500
load_module: TweetSpread
max_time: 5
num_trials: 1
# interval: 1
network_params:
    path: ../2_graph_builder/graph_500_int_direct.gexf

states:
  0:
    agent_type: TweetSpread.OpinionLeader
  18788:
    agent_type: TweetSpread.Bot
  1855:
    agent_type: TweetSpread.Bot
  12116:
    agent_type: TweetSpread.Bot
  32115:
    agent_type: TweetSpread.Bot
  35283:
    agent_type: TweetSpread.Bot
  10491:
    agent_type: TweetSpread.Bot
  132:
    agent_type: TweetSpread.Bot
  17137:
    agent_type: TweetSpread.Bot
  8527:
    agent_type: TweetSpread.Bot
  36313:
    agent_type: TweetSpread.Bot



network_agents:
    - agent_type: User
      weight: 9
      state:
        id: not_exposed

#environment_params:
  