load_module: entities
network_agents:
- agent_type: entities.User
  state:
    id: not_exposed
  weight: 9
network_params:
  path: ./data/graph/500-users.gexf
states:
  0:
    agent_type: entities.OpinionLeader
  54:
    agent_type: entities.Bot
  56:
    agent_type: entities.Bot
  57:
    agent_type: entities.Bot
  58:
    agent_type: entities.Bot
  59:
    agent_type: entities.Bot
  60:
    agent_type: entities.Bot
  37487:
    agent_type: entities.Bot
  37488:
    agent_type: entities.Bot
  37489:
    agent_type: entities.Bot
  37490:
    agent_type: entities.Bot
