load_module: entities
max_time: 5
name: random_1000
network_agents:
- agent_type: entities.User
  state:
    id: not_exposed
  weight: 9
network_params:
  path: "/mnt/c/Users/Vittorio/Documents/universit\xE0/SistemiComplessi/STN/STN/streamlit_app/data/graph/1000-users.gexf"
num_trials: 1
states:
  0:
    agent_type: entities.OpinionLeader
  13092:
    agent_type: entities.Bot
  33502:
    agent_type: entities.Bot
  39858:
    agent_type: entities.Bot
  48687:
    agent_type: entities.Bot
  72790:
    agent_type: entities.Bot
  75670:
    agent_type: entities.Bot
  77765:
    agent_type: entities.Bot
  88676:
    agent_type: entities.Bot
  91500:
    agent_type: entities.Bot
  105429:
    agent_type: entities.Bot
