---
name: MyExampleSimulation
load_module: TweetSpread
max_time: 5
num_trials: 1
# interval: 1
network_params:
    generator: barabasi_albert_graph
    n: 300
    m: 2
network_agents:
    - agent_type: NotActive
      weight: 3
      state:
        id: not_exposed
    - agent_type: AlmostActive
      weight: 4
      state:
        id: not_exposed
    - agent_type: Active
      weight: 3
      state:
        id: not_exposed
environment_params:
