---
name: MyExampleSimulation
load_module: TweetSpread
max_time: 100
num_trials: 1
interval: 2
network_params:
    generator: barabasi_albert_graph
    n: 300
    m: 2
network_agents:
    - agent_type: NotActive
      weight: 4
      state:
        id: not_exposed
    - agent_type: AlmostActive
      weight: 3
      state:
        id: not_exposed
    - agent_type: Active
      weight: 3
      state:
        id: not_exposed
environment_params:
    prob_neighbor_spread: 0.5
    prob_search_spread: 0.5
    prob_be_infected: 1
