---
name: random_500
load_module: TweetSpread
max_time: 5
num_trials: 1
# interval: 1
network_params:
    path: ../2_graph_builder/graph_500_int_direct.gexf

states:
  0:
    agent_type: TweetSpread.OpinionLeader
  30903:
    agent_type: TweetSpread.Bot
  24459:
    agent_type: TweetSpread.Bot
  17600:
    agent_type: TweetSpread.Bot
  28908:
    agent_type: TweetSpread.Bot
  16631:
    agent_type: TweetSpread.Bot
  16105:
    agent_type: TweetSpread.Bot
  16854:
    agent_type: TweetSpread.Bot
  13368:
    agent_type: TweetSpread.Bot
  23469:
    agent_type: TweetSpread.Bot
  9659:
    agent_type: TweetSpread.Bot



network_agents:
    - agent_type: User
      weight: 9
      state:
        id: not_exposed

#environment_params:
  