---
name: MyExampleSimulation
load_module: TweetSpread
max_time: 5
num_trials: 1
# interval: 1
network_params:
    path: ../2_graph_builder/graph_200_int_direct.gexf

states:
  0:
    agent_type: TweetSpread.OpinionLeader
  1:
    agent_type: TweetSpread.Bot
  10:
    agent_type: TweetSpread.Bot
  100:
    agent_type: TweetSpread.Bot
  520:
    agent_type: TweetSpread.Bot
  1200:
    agent_type: TweetSpread.Bot

network_agents:

    - agent_type: User
      weight: 9
      state:
        id: not_exposed

#environment_params:
